title: ZÜB
tagline: A distributed package index for Zig
remote_theme: javanile/package-manager@main
logo: https://raw.githubusercontent.com/javanile/zub/main/assets/images/logo.png

brand_font_url: "https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
brand_font_family: "'Montserrat', sans-serif"
brand_font_weight: 900
brand_font_style: normal

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      type: "sets"
    values:
      _hide_content: true
  - scope:
      path: "index.html"
    values:
      body_class: "show_hero_search"
  - scope:
      type: "categories"
    values:
      body_class: "page-packages"

collections:
  packages:
    output: true
    permalink: /:collection/:name
  categories:
    output: true
    permalink: /:collection/:name

jekyll-archives:
  enabled:
    - categories
    - tags
  permalinks:
    category: /cat/:name/

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENCE
  - security/*
  - stats/*
  - sync/*
  - Makefile
